name: Champions
description: Calling all Champions Template
title: Calling All Champions - ${date}
labels:
  - event
  - needs champion
assignees:
  - anguspiv
body:
  - type: markdown
    attributes:
      value: |
        Hey Everyone,

        The next first Tuesday of the month is

  - type: input
    id: date
    attributes:
      label: Date
      description: The next first Tuesday of the month
      placeholder: May 13, 2025
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Please create new issues when you get the chance.

        As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). We ask that our champions help guests adhere to the Code of Conduct, and let guests know they can reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team). 

        Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

        Previous Lunch Locations include:
        - Santa Monica
        - Baldwin Hills / Crenshaw / Leimert Park
        - Atwater Village / Eagle Rock

  - type: dropdown
    id: champions
    attributes:
      label: Previous Champions
      description: Ping previous champions to see if they can help out
      multiple: true
      options:
        - "@anguspiv"
        - "@StevenKitzes"
        - "@gr2m"
        - "@davidguttman"
        - "@jarrettch"
      default: 0

  - type: markdown
    attributes:
      value: |
        If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

        If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!
